services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    buildCommand: ""  # ✅ جيد أن تتركها فارغة
    envVars:
      - key: APP_ENV
        value: production
